system:
  server-name: go-admin
mysql:
  host: 127.0.0.1
  port: 3306
  db-name: go-admin
  config: charset=utf8mb4&parseTime=True&loc=Local
  user: root
  password: 123456!
  log-mode: info
  max-idle-conn: 10
  max-open-conn: 100

zap:
  level: debug
  prefix: '[github.com/Dlimingliang/go-admin]'
  format: console
  director: log
  encode-level: LowercaseLevelEncoder
  stacktrace-key: stacktrace
  show-line: true
  max-age: 0 #日志保留天数
  max-size: 5 #单个日志大小 单位M
  max-backups: 10 #最大日志数量
  log-in-file: false #开发环境可不打印
