mysql:
  host: 127.0.0.1
  port: 3306
  db-name: go-admin
  user: root
  password: 123456!
  log-mode: info

zap:
  level: info
  prefix: '[github.com/Dlimingliang/go-admin]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
