definitions:
  model.Menu:
    properties:
      CreatedAt:
        type: string
      ID:
        type: integer
      UpdatedAt:
        type: string
      children:
        items:
          $ref: '#/definitions/model.Menu'
        type: array
      component:
        description: 前端文件路径
        type: string
      hidden:
        description: 是否在列表隐藏
        type: boolean
      icon:
        description: 图标
        type: string
      name:
        description: 路由名称
        type: string
      parent_id:
        description: 父菜单id
        type: integer
      path:
        description: 路由path
        type: string
      sort:
        description: 排序
        type: integer
      title:
        description: 菜单名称
        type: string
    type: object
  model.Role:
    properties:
      CreatedAt:
        type: string
      UpdatedAt:
        type: string
      authorityId:
        description: 角色编码
        type: string
      authorityName:
        description: 角色名称
        type: string
      children:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      defaultRouter:
        description: 默认菜单(默认dashboard)
        type: string
      parentId:
        description: 父角色ID
        type: string
    type: object
  model.User:
    properties:
      CreatedAt:
        type: string
      ID:
        type: integer
      UpdatedAt:
        type: string
      email:
        type: string
      headerImg:
        type: string
      nickName:
        type: string
      phone:
        type: string
      userName:
        type: string
    type: object
  request.ById:
    properties:
      id:
        description: 主键ID
        type: integer
    required:
    - id
    type: object
  request.ChangeUserInfo:
    properties:
      email:
        description: 邮件
        type: string
      headerImg:
        description: 头像
        type: string
      id:
        description: ID
        type: integer
      nickName:
        description: 昵称
        type: string
      phone:
        description: 电话
        type: string
    type: object
  request.MenuInfo:
    properties:
      ID:
        type: integer
      component:
        description: 前端文件路径
        maxLength: 40
        minLength: 1
        type: string
      hidden:
        description: 是否隐藏
        type: boolean
      icon:
        description: icon
        maxLength: 20
        minLength: 1
        type: string
      name:
        description: 路由名称
        maxLength: 20
        minLength: 1
        type: string
      parentId:
        description: 父ID
        type: string
      path:
        description: 路由path
        maxLength: 20
        minLength: 1
        type: string
      sort:
        description: 排序
        maximum: 999
        minimum: 1
        type: integer
      title:
        description: 菜单名称
        maxLength: 20
        minLength: 1
        type: string
    required:
    - component
    - hidden
    - icon
    - name
    - parentId
    - path
    - sort
    - title
    type: object
  request.PageInfo:
    properties:
      keyword:
        description: 关键字
        type: string
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页大小
        type: integer
    required:
    - page
    - pageSize
    type: object
  request.Register:
    properties:
      email:
        description: 邮件
        type: string
      headerImg:
        description: 头像
        type: string
      nickName:
        description: 昵称
        type: string
      password:
        description: 密码
        maxLength: 16
        minLength: 6
        type: string
      phone:
        description: 电话
        maxLength: 11
        minLength: 11
        type: string
      userName:
        description: 用户名
        maxLength: 50
        minLength: 1
        type: string
    required:
    - password
    - phone
    - userName
    type: object
  request.RoleInfo:
    properties:
      authorityId:
        type: string
      authorityName:
        type: string
      parentId:
        type: string
    required:
    - authorityId
    - authorityName
    - parentId
    type: object
  response.MenuResult:
    properties:
      menu:
        $ref: '#/definitions/model.Menu'
        description: 菜单信息
    type: object
  response.MenuTree:
    properties:
      menuList:
        description: 菜单树
        items:
          $ref: '#/definitions/model.Menu'
        type: array
    type: object
  response.PageResult:
    properties:
      list:
        description: 列表
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页大小
        type: integer
      total:
        description: 总数
        type: integer
    type: object
  response.Response:
    properties:
      code:
        description: 编码
        type: integer
      data:
        description: 数据
      msg:
        description: 错误信息
    type: object
  response.RoleResult:
    properties:
      authority:
        $ref: '#/definitions/model.Role'
    type: object
  response.UserResult:
    properties:
      user:
        $ref: '#/definitions/model.User'
        description: 用户信息
    type: object
info:
  contact: {}
  description: GA管理平台
  title: GA-API接口文档
paths:
  /authority/createAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RoleInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 角色信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.RoleResult'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 新增角色
      tags:
      - 角色相关接口
  /authority/deleteAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ById'
      produces:
      - application/json
      responses:
        "200":
          description: 删除角色
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除角色
      tags:
      - 角色相关接口
  /authority/getAuthorityList:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 角色列表信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取角色列表
      tags:
      - 角色相关接口
  /authority/updateAuthority:
    post:
      consumes:
      - application/json
      parameters:
      - description: 角色信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.RoleInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 更新角色
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 修改角色
      tags:
      - 角色相关接口
  /menu/addBaseMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: 菜单信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MenuInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 菜单信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.MenuResult'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 新增菜单
      tags:
      - 菜单相关接口
  /menu/deleteBaseMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ById'
      produces:
      - application/json
      responses:
        "200":
          description: 删除菜单
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除菜单
      tags:
      - 菜单相关接口
  /menu/getBaseMenuById:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ById'
      produces:
      - application/json
      responses:
        "200":
          description: 菜单信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.MenuResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 根据ID获取菜单
      tags:
      - 菜单相关接口
  /menu/getBaseMenuTree:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 菜单树信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.MenuTree'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取菜单树
      tags:
      - 菜单相关接口
  /menu/getMenuList:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 菜单列表信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取菜单列表
      tags:
      - 菜单相关接口
  /menu/updateBaseMenu:
    post:
      consumes:
      - application/json
      parameters:
      - description: 菜单信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.MenuInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 更新菜单
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 修改菜单
      tags:
      - 菜单相关接口
  /user/admin_register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名, 昵称, 密码, 角色ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: 用户注册账号,返回包括用户信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.UserResult'
              type: object
      security:
      - ApiKeyAuth: []
      summary: 注册管理员
      tags:
      - 用户相关接口
  /user/deleteUser:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ById'
      produces:
      - application/json
      responses:
        "200":
          description: 删除用户
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - 用户相关接口
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 分页获取用户列表,返回包括列表,总数,页码,每页数量
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - 用户相关接口
  /user/resetPassword:
    post:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ById'
      produces:
      - application/json
      responses:
        "200":
          description: 重置密码
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 重置密码
      tags:
      - 用户相关接口
  /user/setUserInfo:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID, 用户名, 昵称, 头像链接
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ChangeUserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 修改管理员信息
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 修改管理员信息
      tags:
      - 用户相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
