definitions:
  request.PageInfo:
    properties:
      keyword:
        description: 关键字
        type: string
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页大小
        type: integer
    required:
    - page
    - pageSize
    type: object
  response.PageResult:
    properties:
      list:
        description: 列表
      page:
        description: 页码
        type: integer
      pageSize:
        description: 每页大小
        type: integer
      total:
        description: 总数
        type: integer
    type: object
  response.Response:
    properties:
      code:
        description: 编码
        type: integer
      data:
        description: 数据
      msg:
        description: 错误信息
    type: object
info:
  contact: {}
  description: GA管理平台
  title: GA-API接口文档
paths:
  /user/getUserList:
    post:
      consumes:
      - application/json
      parameters:
      - description: 页码, 每页大小
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.PageInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 分页获取用户列表,返回包括列表,总数,页码,每页数量
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取用户列表
      tags:
      - 用户相关接口
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
